### ISSUE TITLE
How many parameters does SPOC have?

### ISSUE THREAD

**Issue by BurgerAndreas** [allenai/spoc-robot-training#20]
Thank you for making the repo public!

I was wondering: How many trainable parameters are there in total?

**Comment by KuoHaoZeng** [comment]
Thank you for the interests in our project!
We didn't do an end-to-end finetuning, so the total trainable parameters is 226M, including the final causal transformer decoder and the transformer encoder to fuse `text_goal_feat` as well as `visual_feat`, according to the PyTorch Lightning log.
