### ISSUE TITLE
Pretrained Checkpoint unavailable

### ISSUE THREAD

**Issue by ConnerQiu** [allenai/spoc-robot-training#22]
Hi guys, thanks for your solid work for the community. I think SPOC have made a big advancement.

I meet a problem when I try to download the pretrained checkpoint with the url "https://pub-bebbada739114fa1aa96aaf25c873a66.r2.dev/checkpoints/DINOv2-ViTs-3-CHORES-S". where I get a error message of "2024-04-12 08:50:42 ERROR 404: Not Found." 

Looks like the link is broken. Can you kindly help check it.

**Comment by KuoHaoZeng** [comment]
We download the checkpoint and its config file using 
[https://pub-bebbada739114fa1aa96aaf25c873a66.r2.dev/checkpoints/DINOv2-ViTs-3-CHORES-S/checkpoint_final.ckpt](https://pub-bebbada739114fa1aa96aaf25c873a66.r2.dev/checkpoints/DINOv2-ViTs-3-CHORES-S/checkpoint_final.ckpt) and [https://pub-bebbada739114fa1aa96aaf25c873a66.r2.dev/checkpoints/DINOv2-ViTs-3-CHORES-S/config.yaml](https://pub-bebbada739114fa1aa96aaf25c873a66.r2.dev/checkpoints/DINOv2-ViTs-3-CHORES-S/config.yaml), separately, and put both files into a folder named `DINOv2-ViTs-3-CHORES-S` after download. Both links work for me.
Please refer to the checkpoint download [script](https://github.com/allenai/spoc-robot-training/blob/main/scripts/download_trained_ckpt.py#L25) for more details.

**Comment by ConnerQiu** [comment]
Thanks! Problem solved
