### ISSUE TITLE
Training from scrach

### ISSUE THREAD

**Issue by rginjapan** [allenai/spoc-robot-training#24]
Training from scratch. Set "--resume" (along with "--run_id" and "--step") to resume from a checkpoint.
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/3
Training from scratch. Set "--resume" (along with "--run_id" and "--step") to resume from a checkpoint.
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/3
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 3 processes
----------------------------------------------------------------------------------------------------

Logging everything in  /media/sly2/860EVO/spoc-robot-training/log/YBqLm86o
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2]
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

  | Name          | Type                      | Params
------------------------------------------------------------
0 | model         | EarlyFusionCnnTransformer | 226 M 
1 | frames_metric | SumMetric                 | 0     
------------------------------------------------------------
226 M     Trainable params
0         Non-trainable params
226 M     Total params
906.443   Total estimated model params size (MB)
Sanity Checking DataLoader 0:   0%|                             

Then the error occurs:
  File "/media/spoc-robot-training/online_evaluation/local_logging_utils.py", line 66, in version
    return self._experiment.id
AttributeError: 'NoneType' object has no attribute 'id'

This is the command I used:
python -m training.offline.train_pl --dataset_version /media/spoc-robot-training/training_data/fifteen/ObjectNavType --eval_every 50 --precision 16-mixed --input_sensors raw_navigation_camera raw_manipulation_camera last_actions an_object_is_in_hand  --per_gpu_batch 4 --sliding_window 50 --model EarlyFusionCnnTransformer --model_version siglip_base_3  --lr 0.0002 --wandb_logging False --output_dir /media/spoc-robot-training/log

**Comment by tony10101105** [comment]
Hi,

This error is because that, in "fifteen" /ObjectNavType, some house ids in the house_id_to_sub_house_id_train.json are not in the downloaded mp4 files, while the program loads data using house_id_to_sub_house_id_train.json. So an error arises when program catches nothing.
To solve this issue, you can filter out house ids that are in house_id_to_sub_house_id_train.json but not downloaded mp4 files (creating a new json file to replace the old one).

**Comment by ehsanik** [comment]
Hi, Thanks for the solution Tony :)
