### ISSUE TITLE
An issues ablout generate depth image

### ISSUE THREAD

**Issue by wulalala1999** [allenai/spoc-robot-training#40]
Hi, I am trying to generate the depth image for each rgb frame, but i don't know the specific parameters of the two cameras  
e.g. horizons, FOV. Can you offer some details about the parameters? 
 By the way, can you offer the pipeline code of the dataset collection. 

Thanks so much!

**Comment by ehsanik** [comment]
For generating the depth image you can set the flag `renderDepthImage=True` when you initialize the environment. Then, you can get the depth frame by calling controller.navigation_depth_frame or controller.manipulation_depth_frame. 

FOV, horizon and other camera parameters will be the same as the RGB camera.

We haven't released the data generation pipeline yet but we will keep you posted.
