### ISSUE TITLE
An issue about the evaluation.

### ISSUE THREAD

**Issue by yusirhhh** [allenai/spoc-robot-training#43]
When I run the test script, I encounter the issue depicted in the following image. Despite this, the program is able to continue running. Why does this error occur, and could it potentially affect the final results?
![image](https://github.com/user-attachments/assets/9cf84b66-9de7-4519-a576-938c25251a38)

**Comment by ehsanik** [comment]
The problem is your ai2thor gets timed out. This is usually a low memory issue. Try rerunning with fewer number of workers and it should work fine.
