### ISSUE TITLE
An issue with evaluation

### ISSUE THREAD

**Issue by altairje** [allenai/spoc-robot-training#51]
I try to run this:
```
python -m training.offline.online_eval --shuffle --eval_subset minival --output_basedir /home/altair/spoc-robot-training/output  --test_augmentation --task_type TASK_TYPE  --input_sensors raw_navigation_camera raw_manipulation_camera last_actions an_object_is_in_hand  --house_set objaverse --wandb_logging False --num_workers 1  --gpu_devices 0 --training_run_id SigLIP-ViTb-3-CHORES-S --local_checkpoint_dir /mnt/vol1/weights/spoc_eval
```
but I got an error:
<img width="1268" alt="image" src="https://github.com/user-attachments/assets/33ead50e-dc2e-458f-aa95-f96f485b350a">

I downloaded objaverse_houses, but only got val.jsonl.gz file there

<img width="571" alt="image" src="https://github.com/user-attachments/assets/d8bfb32a-0299-410b-833e-64d1e4e119e7">

**Comment by ehsanik** [comment]
Hi, 

You are setting the routes incorrectly. You need to pass in the objaverse house directory as `/mnt/vol1/datasets/objaverse_houses/houses_2023_07_28`. 

I you see in the error message the code is looking for them in `/mnt/vol1/datasets/objaverse_houses/` and can't find them.
